import type { IStorage } from "./storage";
import { logger } from "./logger";

/**
 * 실제 운영중인 정부지원사업 및 투자유치 프로그램 데이터
 * API 크롤링 전 기본 데이터로 활용 (source: "manual")
 */
export async function seedRealData(storage: IStorage) {
  logger.info("실제 프로그램 데이터를 추가합니다...");

  // =============================================
  // 실제 정부지원사업 (2026년 기준 매년 반복 모집)
  // =============================================
  const govPrograms = [
    // --- 창업진흥원 주관 패키지 사업 ---
    {
      title: "2026년 예비창업패키지",
      organization: "창업진흥원",
      supportType: "예비창업패키지" as const,
      status: "모집중" as const,
      description: "혁신적인 기술창업 아이디어를 보유한 예비창업자를 대상으로 사업화 자금(최대 1억원), 창업교육, 멘토링을 패키지로 지원합니다. 주관기관별로 특화 분야가 다르며, 전국 약 40개 주관기관에서 운영합니다.",
      targetAudience: "예비창업자(사업자등록 전) 또는 사업자등록 후 3년 미만인 자",
      supportAmount: "최대 1억원 (평균 4,600만원)",
      applicationMethod: "K-Startup(www.k-startup.go.kr) 온라인 접수 후 주관기관 선택",
      applicationUrl: "https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do",
      region: "전국",
      startDate: "2026-01-20",
      endDate: "2026-04-30",
      sourceId: "real-gov-1",
      source: "manual",
    },
    {
      title: "2026년 초기창업패키지",
      organization: "창업진흥원",
      supportType: "초기창업패키지" as const,
      status: "모집중" as const,
      description: "창업 3년 이내 초기 스타트업을 대상으로 사업화 자금 및 전문 멘토 매칭을 통한 집중 육성 프로그램입니다. 주관기관별 특화 분야(AI, 바이오, 제조 등) 선택 가능합니다.",
      targetAudience: "창업 3년 이내 기업(업력 기준) 대표자",
      supportAmount: "최대 1억원",
      applicationMethod: "K-Startup 온라인 접수",
      applicationUrl: "https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do",
      region: "전국",
      startDate: "2026-02-01",
      endDate: "2026-05-15",
      sourceId: "real-gov-2",
      source: "manual",
    },
    {
      title: "2026년 창업도약패키지",
      organization: "중소벤처기업부",
      supportType: "도약패키지" as const,
      status: "모집중" as const,
      description: "창업 3~7년차 도약기 스타트업의 성장을 위한 사업화 자금, 글로벌 진출, 후속 투자연계를 패키지로 지원합니다. 기존 창업성장기술개발(디딤돌)과 통합 운영됩니다.",
      targetAudience: "창업 3~7년 이내 중소기업 대표자",
      supportAmount: "최대 3억원",
      applicationMethod: "K-Startup 온라인 접수",
      applicationUrl: "https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do",
      region: "전국",
      startDate: "2026-03-01",
      endDate: "2026-04-15",
      sourceId: "real-gov-3",
      source: "manual",
    },
    // --- TIPS ---
    {
      title: "2026년 TIPS(민간투자주도형 기술창업지원)",
      organization: "중소벤처기업부 / TIPS 운영사",
      supportType: "기술개발" as const,
      status: "모집중" as const,
      description: "민간 엔젤투자사(TIPS 운영사)가 우수 기술 스타트업을 발굴·추천하면, 정부가 R&D 자금(최대 5억원)과 창업사업화 자금(1억원)을 매칭 지원합니다. 엔젤투자 1억원 + 정부 R&D 5억원 + 사업화 1억원의 패키지입니다.",
      targetAudience: "TIPS 운영사의 투자를 받은(또는 추천을 받은) 창업 7년 이내 기술 스타트업",
      supportAmount: "R&D 최대 5억원 + 사업화 1억원 + 해외마케팅 1억원",
      applicationMethod: "TIPS 운영사를 통한 추천 후 K-Startup 온라인 접수",
      applicationUrl: "https://www.jointips.or.kr/biz_list.php",
      region: "전국",
      startDate: "2026-01-01",
      endDate: "2026-12-31",
      sourceId: "real-gov-4",
      source: "manual",
    },
    // --- 창업성장기술개발 ---
    {
      title: "2026년 창업성장기술개발사업 (디딤돌)",
      organization: "중소벤처기업부",
      supportType: "기술개발" as const,
      status: "모집예정" as const,
      description: "기술 기반 창업기업의 R&D를 지원하는 사업입니다. 디딤돌(초기)과 전략형(성장) 트랙으로 나뉘며, 과제 수행 후 기술 사업화를 목표로 합니다.",
      targetAudience: "창업 7년 이내 기술 기반 중소기업",
      supportAmount: "디딤돌: 최대 2억원, 전략형: 최대 3억원 (2년)",
      applicationMethod: "중소기업기술개발사업 종합관리시스템(SMTECH) 접수",
      applicationUrl: "https://www.smtech.go.kr/front/ifg/no/notice02_list.do",
      region: "전국",
      startDate: "2026-05-01",
      endDate: "2026-06-30",
      sourceId: "real-gov-5",
      source: "manual",
    },
    // --- 청년창업사관학교 ---
    {
      title: "2026년 청년창업사관학교",
      organization: "중소벤처기업부 / 창업진흥원",
      supportType: "사업화지원" as const,
      status: "모집중" as const,
      description: "만 39세 이하 (예비)창업자를 대상으로 입주공간, 사업화자금(최대 1억원), 코칭, 기술지원 등을 1년간 집중 지원하는 프로그램입니다. 전국 8개 캠퍼스에서 운영됩니다.",
      targetAudience: "만 39세 이하 예비창업자 또는 창업 3년 이내 대표자",
      supportAmount: "최대 1억원 (사업화 자금)",
      applicationMethod: "K-Startup 온라인 접수",
      applicationUrl: "https://start.kosmes.or.kr/lms_main.do",
      region: "전국",
      startDate: "2026-02-15",
      endDate: "2026-04-10",
      sourceId: "real-gov-6",
      source: "manual",
    },
    // --- 소셜벤처 ---
    {
      title: "2026년 사회적기업가 육성사업",
      organization: "한국사회적기업진흥원",
      supportType: "사업화지원" as const,
      status: "모집중" as const,
      description: "사회문제 해결형 비즈니스 모델을 가진 (예비)사회적기업가를 발굴·육성합니다. 사업화 자금, 교육, 멘토링, 네트워킹을 지원합니다.",
      targetAudience: "사회적 경제 분야 (예비)창업자",
      supportAmount: "팀당 최대 5,000만원",
      applicationMethod: "사회적기업 통합정보시스템",
      applicationUrl: "https://www.socialenterprise.or.kr/social/board/list.do?board_code=BO04",
      region: "전국",
      startDate: "2026-03-01",
      endDate: "2026-05-31",
      sourceId: "real-gov-7",
      source: "manual",
    },
    // --- KOTRA 해외진출 ---
    {
      title: "2026년 스타트업 해외진출(Born Global) 지원",
      organization: "KOTRA",
      supportType: "해외진출" as const,
      status: "모집예정" as const,
      description: "글로벌 시장 진출을 목표로 하는 스타트업에 현지 시장조사, 바이어 매칭, 해외 전시회·데모데이 참가, 현지 법인 설립 지원 등을 제공합니다.",
      targetAudience: "해외진출 희망 스타트업 및 중소기업",
      supportAmount: "기업당 최대 3,000만원",
      applicationMethod: "KOTRA 수출바우처 또는 개별 사업 공고 통해 접수",
      applicationUrl: "https://www.kotra.or.kr/bigdata/biz/annce/pbanc/list.do",
      region: "전국",
      startDate: "2026-05-01",
      endDate: "2026-06-30",
      sourceId: "real-gov-8",
      source: "manual",
    },
    // --- 스마트공장 ---
    {
      title: "2026년 스마트공장 보급·확산사업",
      organization: "중소벤처기업부 / 스마트제조혁신추진단",
      supportType: "기술개발" as const,
      status: "모집중" as const,
      description: "중소·중견 제조기업의 스마트공장 도입을 지원합니다. 기초/고도화 수준에 따라 구축비, 컨설팅, 교육을 단계별로 제공합니다.",
      targetAudience: "제조업 영위 중소·중견기업",
      supportAmount: "기초 최대 4,000만원 ~ 고도화 최대 1.5억원 (정부 50% 매칭)",
      applicationMethod: "스마트제조혁신포털(smart-factory.kr) 온라인 접수",
      applicationUrl: "https://www.smart-factory.kr/smartFactoryIntro",
      region: "전국",
      startDate: "2026-02-01",
      endDate: "2026-04-30",
      sourceId: "real-gov-9",
      source: "manual",
    },
    // --- 중소기업 정책자금 ---
    {
      title: "2026년 중소기업 정책자금(창업기업지원자금)",
      organization: "중소벤처기업부 / 중소벤처기업진흥공단",
      supportType: "정책자금" as const,
      status: "모집중" as const,
      description: "창업 7년 이내 중소기업에 시설자금·운전자금을 저금리(연 약 2~3%)로 융자 지원합니다. 혁신창업형/일반창업형으로 구분됩니다.",
      targetAudience: "창업 7년 이내 중소기업기본법상 중소기업",
      supportAmount: "기업당 최대 100억원 (연 1.86~2.76% 금리)",
      applicationMethod: "중소기업 정책자금 누리집(kosmes.or.kr) 접수",
      applicationUrl: "https://www.kosmes.or.kr/sbc/SH/SBI/SHSBI008M0.do",
      region: "전국",
      startDate: "2026-01-02",
      endDate: "2026-11-30",
      sourceId: "real-gov-10",
      source: "manual",
    },
    // --- 기술보증기금 ---
    {
      title: "2026년 혁신스타트업 성장지원 프로그램",
      organization: "기술보증기금(KIBO)",
      supportType: "정책자금" as const,
      status: "모집중" as const,
      description: "기술력 우수 스타트업을 대상으로 기술보증 우대, 보증연계투자, 기술평가를 통한 자금 지원 프로그램입니다.",
      targetAudience: "기술력 우수 스타트업 (기보 기술평가 기준)",
      supportAmount: "보증 최대 30억원 / 보증연계투자 최대 15억원",
      applicationMethod: "기술보증기금 영업점 방문 또는 온라인 신청",
      applicationUrl: "https://www.kibo.or.kr/src/guaranty/guarantyIntro.do",
      region: "전국",
      startDate: "2026-01-01",
      endDate: "2026-12-31",
      sourceId: "real-gov-11",
      source: "manual",
    },
    // --- 서울창업허브 ---
    {
      title: "2026년 서울창업허브 입주기업 모집",
      organization: "서울산업진흥원(SBA)",
      supportType: "시설_공간" as const,
      status: "모집중" as const,
      description: "서울 마포구 서울창업허브 입주공간(사무실, 코워킹스페이스)을 제공하고, 멘토링, 네트워킹, 투자유치 연계 프로그램을 운영합니다.",
      targetAudience: "창업 7년 이내 서울 소재 기업 또는 서울 입주 희망 기업",
      supportAmount: "시세 30% 수준 임대료 + 멘토링/네트워킹 무료",
      applicationMethod: "서울창업허브 홈페이지 입주 신청",
      applicationUrl: "https://seoulstartuphub.com/support/apply",
      region: "서울",
      startDate: "2026-01-15",
      endDate: "2026-12-31",
      sourceId: "real-gov-12",
      source: "manual",
    },
    // --- 바이오 특화 ---
    {
      title: "2026년 범부처 통합 바이오 R&D 지원",
      organization: "한국보건산업진흥원(KHIDI)",
      supportType: "기술개발" as const,
      status: "모집예정" as const,
      description: "바이오·의료기기·디지털헬스케어 분야의 기술개발 및 사업화를 지원합니다. 시제품 제작, 인허가, 비임상/임상시험 비용 지원 포함.",
      targetAudience: "바이오·헬스케어 분야 중소벤처기업 및 연구기관",
      supportAmount: "과제당 최대 3억원 (최대 3년)",
      applicationMethod: "보건산업진흥원 R&D 사업관리시스템(HITS)",
      applicationUrl: "https://www.khidi.or.kr/board/view?pageNum=1&rowCnt=10&menuId=MENU02309",
      region: "전국",
      startDate: "2026-05-15",
      endDate: "2026-07-15",
      sourceId: "real-gov-13",
      source: "manual",
    },
    // --- 농식품 ---
    {
      title: "2026년 농식품 벤처 창업인큐베이팅 지원",
      organization: "농림식품기술기획평가원(iPET)",
      supportType: "사업화지원" as const,
      status: "모집중" as const,
      description: "농업·식품 분야 기술 스타트업의 사업화를 위한 자금, 시장검증, 투자유치 연계를 지원합니다.",
      targetAudience: "농식품 분야 창업 7년 이내 중소기업",
      supportAmount: "최대 8,000만원",
      applicationMethod: "농식품 기술사업화 지원센터",
      applicationUrl: "https://www.ipet.re.kr/board/list.do?boardId=BBS_0000008",
      region: "전국",
      startDate: "2026-03-01",
      endDate: "2026-05-10",
      sourceId: "real-gov-14",
      source: "manual",
    },
    // --- 창업멘토링 ---
    {
      title: "2026년 창업기업 전문멘토링(전담멘토)",
      organization: "창업진흥원",
      supportType: "멘토링_컨설팅" as const,
      status: "모집중" as const,
      description: "선배 창업자 및 분야별 전문가를 전담멘토로 매칭하여 1:1 맞춤형 멘토링을 제공합니다. 경영, 기술, 법률, 세무, 마케팅 등 분야별 지원.",
      targetAudience: "창업 7년 이내 기업 대표자",
      supportAmount: "무료 (멘토링 회당 50만원 상당)",
      applicationMethod: "K-Startup 전담멘토 매칭 시스템",
      applicationUrl: "https://www.k-startup.go.kr/web/contents/bizpbanc-ongoing.do",
      region: "전국",
      startDate: "2026-01-01",
      endDate: "2026-12-31",
      sourceId: "real-gov-15",
      source: "manual",
    },
    // --- 경기도 특화 ---
    {
      title: "2026년 경기도 청년 창업지원 프로그램",
      organization: "경기도경제과학진흥원(GBSA)",
      supportType: "사업화지원" as const,
      status: "모집중" as const,
      description: "경기도 소재 만 39세 이하 (예비)창업자를 대상으로 사업화 자금, 교육, 공간을 패키지로 지원합니다.",
      targetAudience: "경기도 거주 만 39세 이하 (예비)창업자",
      supportAmount: "최대 3,000만원",
      applicationMethod: "경기도 창업플랫폼 온라인 접수",
      applicationUrl: "https://www.gbsa.or.kr/board/list.do?boardId=startup_notice",
      region: "경기",
      startDate: "2026-03-10",
      endDate: "2026-04-25",
      sourceId: "real-gov-16",
      source: "manual",
    },
    // --- IITP ---
    {
      title: "2026년 ICT R&D 혁신바우처 지원사업",
      organization: "정보통신기획평가원(IITP)",
      supportType: "기술개발" as const,
      status: "모집중" as const,
      description: "AI, 빅데이터, 클라우드, 블록체인 등 ICT 핵심기술 분야 중소기업의 기술개발을 바우처 방식으로 지원합니다.",
      targetAudience: "ICT 분야 중소·벤처기업",
      supportAmount: "기업당 최대 3억원",
      applicationMethod: "IITP 과제 공모 시스템",
      applicationUrl: "https://www.iitp.kr/kr/1/business/businessNotice/list.it",
      region: "전국",
      startDate: "2026-02-15",
      endDate: "2026-04-10",
      sourceId: "real-gov-17",
      source: "manual",
    },
    // --- 부산 ---
    {
      title: "2026년 부산 지역특화 창업지원(해양·물류·관광)",
      organization: "부산창조경제혁신센터",
      supportType: "사업화지원" as const,
      status: "모집중" as const,
      description: "부산 지역 특화 산업(해양, 물류, 관광, 영화) 분야 스타트업의 사업화를 지원합니다. 입주공간, 자금, 멘토링 포함.",
      targetAudience: "부산 소재(또는 이전 예정) 창업 5년 이내 기업",
      supportAmount: "최대 5,000만원",
      applicationMethod: "부산창조경제혁신센터 홈페이지",
      applicationUrl: "https://ccei.creativekorea.or.kr/busan/custom/notice_list.do",
      region: "부산",
      startDate: "2026-03-15",
      endDate: "2026-05-15",
      sourceId: "real-gov-18",
      source: "manual",
    },
    // --- 대전 ---
    {
      title: "2026년 대전 과학기술 기반 창업 패키지",
      organization: "대전테크노파크",
      supportType: "기술개발" as const,
      status: "모집중" as const,
      description: "대전 대덕연구단지 연계 기술 스타트업 육성 프로그램. 기술이전, R&D 지원, 시제품 제작, 시험인증 등을 지원합니다.",
      targetAudience: "대전 소재 기술창업 기업 (KAIST, ETRI, 대덕 출연연 등 연계)",
      supportAmount: "최대 1억원",
      applicationMethod: "대전테크노파크 홈페이지",
      applicationUrl: "https://www.djtp.or.kr/sub.asp?code=0301",
      region: "대전",
      startDate: "2026-02-20",
      endDate: "2026-04-30",
      sourceId: "real-gov-19",
      source: "manual",
    },
    // --- 여성기업 ---
    {
      title: "2026년 여성기업 종합지원",
      organization: "한국여성경제인협회",
      supportType: "사업화지원" as const,
      status: "모집중" as const,
      description: "여성 대표 기업을 대상으로 경영컨설팅, 판로개척, 수출지원, 금융연계 등을 종합적으로 지원합니다.",
      targetAudience: "여성 대표 중소기업 (여성기업 확인 필요)",
      supportAmount: "프로그램별 상이 (컨설팅 무료, 판로 최대 2,000만원)",
      applicationMethod: "한국여성경제인협회 또는 여성기업종합지원센터",
      applicationUrl: "https://www.wbiz.or.kr/kr/contents/biz/support.do",
      region: "전국",
      startDate: "2026-01-15",
      endDate: "2026-12-31",
      sourceId: "real-gov-20",
      source: "manual",
    },
  ];

  // =============================================
  // 실제 투자유치 프로그램 / 엑셀러레이터 / VC
  // =============================================
  const invPrograms = [
    {
      title: "스파크랩(SparkLabs) 2026년 상반기 배치",
      organization: "스파크랩 (SparkLabs)",
      investorType: "AC" as const,
      description: "글로벌 진출을 목표로 하는 초기 스타트업 대상 3개월 액셀러레이팅 프로그램. 투자금 + 실리콘밸리·아시아 멘토 150명 네트워크 연결. 데모데이 후 후속투자 연계.",
      investmentScale: "팀당 1억원 (지분 5~8%)",
      targetStage: "시드 ~ 프리시리즈A",
      targetIndustry: "AI, SaaS, 헬스테크, 핀테크, 에듀테크",
      contactInfo: "apply@sparklabs.co.kr",
      websiteUrl: "https://www.sparklabs.co.kr",
      applicationUrl: "https://www.sparklabs.co.kr/apply",
      startDate: "2026-03-01",
      endDate: "2026-04-30",
      status: "모집중",
    },
    {
      title: "프라이머(Primer) 시즌 26",
      organization: "프라이머 (Primer)",
      investorType: "AC" as const,
      description: "국내 1세대 액셀러레이터 프라이머의 시드 투자 + 3개월 집중 육성 프로그램. 사업모델 검증, 고객 개발, 후속투자 연계까지 지원.",
      investmentScale: "팀당 5,000만~1억원",
      targetStage: "시드",
      targetIndustry: "산업 무관 (기술기반 스타트업 우대)",
      contactInfo: "contact@primer.kr",
      websiteUrl: "https://www.primer.kr",
      startDate: "2026-04-01",
      endDate: "2026-05-31",
      status: "모집예정",
    },
    {
      title: "매쉬업엔젤스(Mashup Angels) 2026 시드 투자",
      organization: "매쉬업엔젤스",
      investorType: "AC" as const,
      description: "기술 기반 초기 스타트업에 시드 투자. IT, 딥테크, 바이오 분야 집중. 투자 후 후속 라운드까지 밀착 지원.",
      investmentScale: "5,000만~2억원",
      targetStage: "시드 ~ 프리시리즈A",
      targetIndustry: "IT/SW, 딥테크, 바이오",
      contactInfo: "invest@mashupangels.com",
      websiteUrl: "https://www.mashupangels.com",
      status: "모집중",
    },
    {
      title: "블루포인트파트너스 2026 시드 투자",
      organization: "블루포인트파트너스",
      investorType: "AC" as const,
      description: "Pre-Seed~Seed 단계 스타트업 전문 투자. 데모데이를 통한 집중 투자 + 사후 경영 지원. 연간 20~30개팀 투자.",
      investmentScale: "3,000만~1억원",
      targetStage: "Pre-Seed ~ Seed",
      targetIndustry: "전 산업 (기술 혁신 중심)",
      websiteUrl: "https://www.bluepointpartners.com",
      status: "모집중",
    },
    {
      title: "한국투자파트너스 Growth Fund",
      organization: "한국투자파트너스",
      investorType: "VC" as const,
      description: "시리즈A~B 단계 성장 스타트업 대상 투자. IT, 바이오, 콘텐츠 분야 집중. 한국투자증권 그룹 네트워크를 통한 IPO 지원.",
      investmentScale: "10억~50억원",
      targetStage: "시리즈A ~ 시리즈B",
      targetIndustry: "IT/SW, 바이오, 콘텐츠, 핀테크",
      contactInfo: "ir@kipvc.com",
      websiteUrl: "https://www.kipvc.com",
      status: "모집중",
    },
    {
      title: "카카오벤처스 AI/테크 투자",
      organization: "카카오벤처스",
      investorType: "CVC" as const,
      description: "카카오 생태계 시너지 창출 가능한 AI, 딥테크, SaaS 분야 스타트업에 전략적 투자. 카카오 플랫폼 연계 및 기술 협업 기회 제공.",
      investmentScale: "5억~30억원",
      targetStage: "시드 ~ 시리즈A",
      targetIndustry: "AI, 딥테크, SaaS, 모빌리티",
      contactInfo: "ventures@kakao.com",
      websiteUrl: "https://www.kakaoventures.com",
      status: "모집중",
    },
    {
      title: "네이버 D2 스타트업 팩토리(D2SF)",
      organization: "네이버 D2SF",
      investorType: "CVC" as const,
      description: "네이버 기술 플랫폼 연계 가능한 딥테크 스타트업 전문 투자. 네이버 클라우드, 검색, AI 인프라를 활용한 성장 지원.",
      investmentScale: "2억~10억원",
      targetStage: "시드 ~ 프리시리즈A",
      targetIndustry: "AI, 로보틱스, 블록체인, AR/VR, NLP",
      websiteUrl: "https://d2startup.com",
      status: "모집중",
    },
    {
      title: "중소벤처기업부 엔젤투자 매칭펀드",
      organization: "한국엔젤투자협회(KBAN)",
      investorType: "엔젤" as const,
      description: "개인 엔젤투자자의 투자금에 정부가 1:1 매칭으로 자금을 지원합니다. 엔젤투자 활성화와 초기 스타트업 자금 지원이 목표.",
      investmentScale: "매칭 최대 2억원 (엔젤 1 : 정부 1)",
      targetStage: "시드 ~ 프리시리즈A",
      targetIndustry: "전 산업",
      contactInfo: "info@kban.or.kr",
      websiteUrl: "https://www.kban.or.kr",
      startDate: "2026-01-01",
      endDate: "2026-12-31",
      status: "모집중",
    },
    {
      title: "한국성장금융 성장사다리펀드",
      organization: "한국성장금융투자운용",
      investorType: "정책금융" as const,
      description: "정부 정책 목적의 모태펀드 출자를 통한 중소·벤처기업 투자. 신성장동력 산업, 지역 스타트업, 사회적경제 기업 등에 집중.",
      investmentScale: "10억~100억원",
      targetStage: "시리즈A 이상",
      targetIndustry: "신성장동력 산업 전반",
      websiteUrl: "https://www.kgfc.or.kr",
      status: "모집중",
    },
    {
      title: "소풍벤처스(SOPOONG) 임팩트 투자",
      organization: "소풍벤처스",
      investorType: "VC" as const,
      description: "기후테크, ESG, 사회혁신 분야 임팩트 스타트업 전문 투자. 환경·사회적 가치와 수익성을 동시에 추구하는 기업에 투자합니다.",
      investmentScale: "3억~10억원",
      targetStage: "시드 ~ 시리즈A",
      targetIndustry: "기후테크, ESG, 사회혁신, 순환경제",
      contactInfo: "hello@sopoong.net",
      websiteUrl: "https://sopoong.net",
      startDate: "2026-03-01",
      endDate: "2026-06-30",
      status: "모집중",
    },
    {
      title: "본엔젤스벤처파트너스 시드 투자",
      organization: "본엔젤스벤처파트너스",
      investorType: "VC" as const,
      description: "Pre-Seed/Seed 단계 IT 스타트업 전문 투자. 강남 본엔젤스 오피스 입주 기회 및 포트폴리오 네트워킹 지원.",
      investmentScale: "5,000만~3억원",
      targetStage: "Pre-Seed ~ Seed",
      targetIndustry: "IT/SW, 플랫폼, O2O, 커머스",
      websiteUrl: "https://www.bonangels.net",
      status: "모집중",
    },
    {
      title: "KB인베스트먼트 Growth 투자",
      organization: "KB인베스트먼트",
      investorType: "CVC" as const,
      description: "KB금융그룹 계열 VC. 핀테크, 디지털헬스, AI 분야 성장 스타트업에 전략적 투자. KB 금융 인프라 연계 기회.",
      investmentScale: "10억~50억원",
      targetStage: "시리즈A ~ 시리즈B",
      targetIndustry: "핀테크, 디지털헬스, AI, 인슈어테크",
      websiteUrl: "https://www.kbic.co.kr",
      status: "모집중",
    },
  ];

  await storage.bulkUpsertGovernmentPrograms(govPrograms);

  for (const inv of invPrograms) {
    await storage.upsertInvestmentProgram(inv);
  }

  logger.info(`실제 프로그램 데이터 추가 완료: 정부지원사업 ${govPrograms.length}건, 투자유치 ${invPrograms.length}건`);
}
