import type { CategoryKey } from "./models/account";

export interface PopularService {
  id: string;
  name: string;
  url: string;
  category: CategoryKey;
  logoStyle:
    | "symbol_simple"
    | "symbol_refined"
    | "symbol_line"
    | "symbol_color"
    | "cute_character"
    | "wordmark"
    | "emblem"
    | "mascot"
    | "abstract"
    | "other";
  isSubscription: boolean;
  subscriptionCost?: number;
  billingCycle?: "monthly" | "yearly" | "weekly" | "one_time";
  currency?: string;
  deleteDifficulty: "easy" | "medium" | "hard" | "impossible";
  deleteUrl?: string;
  deleteGuide?: string;
}

export const POPULAR_SERVICES: PopularService[] = [
  // ──────── SNS ────────
  {
    id: "instagram",
    name: "Instagram",
    url: "https://www.instagram.com",
    category: "sns",
    logoStyle: "symbol_color",
    isSubscription: false,
    deleteDifficulty: "medium",
    deleteUrl: "https://www.instagram.com/accounts/remove/request/permanent/",
    deleteGuide: "설정 → 계정 → 계정 삭제 → 계정 영구 삭제",
  },
  {
    id: "facebook",
    name: "Facebook",
    url: "https://www.facebook.com",
    category: "sns",
    logoStyle: "symbol_simple",
    isSubscription: false,
    deleteDifficulty: "hard",
    deleteUrl: "https://www.facebook.com/deactivate",
    deleteGuide: "설정 → 개인정보 → 계정 소유권 및 제어 → 비활성화 및 삭제",
  },
  {
    id: "twitter",
    name: "Twitter / X",
    url: "https://x.com",
    category: "sns",
    logoStyle: "symbol_simple",
    isSubscription: false,
    deleteDifficulty: "easy",
    deleteUrl: "https://twitter.com/settings/deactivate",
    deleteGuide: "설정 → 계정 → 계정 비활성화",
  },
  {
    id: "tiktok",
    name: "TikTok",
    url: "https://www.tiktok.com",
    category: "sns",
    logoStyle: "symbol_color",
    isSubscription: false,
    deleteDifficulty: "medium",
    deleteGuide: "프로필 → 설정 → 계정 관리 → 계정 삭제",
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    url: "https://www.linkedin.com",
    category: "sns",
    logoStyle: "symbol_simple",
    isSubscription: false,
    deleteDifficulty: "medium",
    deleteGuide: "설정 → 계정 관리 → 계정 닫기",
  },
  {
    id: "threads",
    name: "Threads",
    url: "https://www.threads.net",
    category: "sns",
    logoStyle: "symbol_simple",
    isSubscription: false,
    deleteDifficulty: "hard",
    deleteGuide: "Instagram 계정과 연동되어 있어 별도 삭제 필요",
  },
  {
    id: "kakaostory",
    name: "카카오스토리",
    url: "https://story.kakao.com",
    category: "sns",
    logoStyle: "symbol_color",
    isSubscription: false,
    deleteDifficulty: "easy",
    deleteGuide: "설정 → 카카오스토리 탈퇴",
  },

  // ──────── 쇼핑 ────────
  {
    id: "coupang",
    name: "쿠팡",
    url: "https://www.coupang.com",
    category: "shopping",
    logoStyle: "wordmark",
    isSubscription: false,
    deleteDifficulty: "medium",
    deleteGuide: "마이쿠팡 → 계정설정 → 회원탈퇴",
  },
  {
    id: "naver-shopping",
    name: "네이버쇼핑",
    url: "https://shopping.naver.com",
    category: "shopping",
    logoStyle: "wordmark",
    isSubscription: false,
    deleteDifficulty: "medium",
    deleteGuide: "네이버 계정 탈퇴 시 함께 삭제",
  },
  {
    id: "11st",
    name: "11번가",
    url: "https://www.11st.co.kr",
    category: "shopping",
    logoStyle: "wordmark",
    isSubscription: false,
    deleteDifficulty: "medium",
    deleteGuide: "마이11번가 → 회원정보 → 회원탈퇴",
  },
  {
    id: "gmarket",
    name: "G마켓",
    url: "https://www.gmarket.co.kr",
    category: "shopping",
    logoStyle: "wordmark",
    isSubscription: false,
    deleteDifficulty: "medium",
    deleteGuide: "My G마켓 → 회원정보 → 회원탈퇴",
  },
  {
    id: "musinsa",
    name: "무신사",
    url: "https://www.musinsa.com",
    category: "shopping",
    logoStyle: "wordmark",
    isSubscription: false,
    deleteDifficulty: "easy",
    deleteGuide: "마이페이지 → 회원정보 수정 → 회원탈퇴",
  },
  {
    id: "ohouse",
    name: "오늘의집",
    url: "https://ohou.se",
    category: "shopping",
    logoStyle: "wordmark",
    isSubscription: false,
    deleteDifficulty: "easy",
    deleteGuide: "마이페이지 → 설정 → 회원탈퇴",
  },
  {
    id: "amazon",
    name: "Amazon",
    url: "https://www.amazon.com",
    category: "shopping",
    logoStyle: "wordmark",
    isSubscription: false,
    deleteDifficulty: "hard",
    deleteUrl: "https://www.amazon.com/privacy/data-deletion",
    deleteGuide: "Account → Close Your Account",
  },
  {
    id: "aliexpress",
    name: "AliExpress",
    url: "https://www.aliexpress.com",
    category: "shopping",
    logoStyle: "wordmark",
    isSubscription: false,
    deleteDifficulty: "hard",
    deleteGuide: "계정 설정 → 개인정보 → 계정 삭제 요청",
  },
  {
    id: "coupang-rocket",
    name: "쿠팡 로켓와우",
    url: "https://www.coupang.com",
    category: "shopping",
    logoStyle: "wordmark",
    isSubscription: true,
    subscriptionCost: 7890,
    billingCycle: "monthly",
    currency: "KRW",
    deleteDifficulty: "easy",
    deleteGuide: "마이쿠팡 → 로켓와우 → 해지",
  },

  // ──────── 금융 ────────
  {
    id: "toss",
    name: "토스",
    url: "https://toss.im",
    category: "finance",
    logoStyle: "symbol_simple",
    isSubscription: false,
    deleteDifficulty: "medium",
    deleteGuide: "전체 → 설정 → 탈퇴하기",
  },
  {
    id: "kakaobank",
    name: "카카오뱅크",
    url: "https://www.kakaobank.com",
    category: "finance",
    logoStyle: "symbol_simple",
    isSubscription: false,
    deleteDifficulty: "hard",
    deleteGuide: "모든 계좌 해지 후 앱에서 탈퇴 가능",
  },
  {
    id: "naverpay",
    name: "네이버페이",
    url: "https://pay.naver.com",
    category: "finance",
    logoStyle: "symbol_color",
    isSubscription: false,
    deleteDifficulty: "medium",
    deleteGuide: "네이버페이 → 설정 → 서비스 해지",
  },
  {
    id: "samsungpay",
    name: "삼성페이",
    url: "https://www.samsung.com/samsung-pay/",
    category: "finance",
    logoStyle: "symbol_simple",
    isSubscription: false,
    deleteDifficulty: "easy",
    deleteGuide: "삼성페이 앱 → 설정 → 서비스 해제",
  },
  {
    id: "kakaopay",
    name: "카카오페이",
    url: "https://www.kakaopay.com",
    category: "finance",
    logoStyle: "symbol_color",
    isSubscription: false,
    deleteDifficulty: "medium",
    deleteGuide: "카카오페이 → 설정 → 서비스 탈퇴",
  },

  // ──────── 엔터테인먼트 ────────
  {
    id: "netflix",
    name: "Netflix",
    url: "https://www.netflix.com",
    category: "entertainment",
    logoStyle: "wordmark",
    isSubscription: true,
    subscriptionCost: 17000,
    billingCycle: "monthly",
    currency: "KRW",
    deleteDifficulty: "easy",
    deleteUrl: "https://www.netflix.com/cancelplan",
    deleteGuide: "계정 → 멤버십 해지",
  },
  {
    id: "youtube-premium",
    name: "YouTube Premium",
    url: "https://www.youtube.com/premium",
    category: "entertainment",
    logoStyle: "symbol_color",
    isSubscription: true,
    subscriptionCost: 14900,
    billingCycle: "monthly",
    currency: "KRW",
    deleteDifficulty: "easy",
    deleteGuide: "YouTube → 유료 멤버십 → 멤버십 해지",
  },
  {
    id: "spotify",
    name: "Spotify",
    url: "https://www.spotify.com",
    category: "entertainment",
    logoStyle: "symbol_simple",
    isSubscription: true,
    subscriptionCost: 10900,
    billingCycle: "monthly",
    currency: "KRW",
    deleteDifficulty: "easy",
    deleteUrl: "https://www.spotify.com/account/",
    deleteGuide: "계정 → 구독 → 플랜 변경 → 해지",
  },
  {
    id: "watcha",
    name: "왓챠",
    url: "https://watcha.com",
    category: "entertainment",
    logoStyle: "wordmark",
    isSubscription: true,
    subscriptionCost: 7900,
    billingCycle: "monthly",
    currency: "KRW",
    deleteDifficulty: "easy",
    deleteGuide: "설정 → 구독 관리 → 해지",
  },
  {
    id: "wavve",
    name: "웨이브",
    url: "https://www.wavve.com",
    category: "entertainment",
    logoStyle: "wordmark",
    isSubscription: true,
    subscriptionCost: 7900,
    billingCycle: "monthly",
    currency: "KRW",
    deleteDifficulty: "easy",
    deleteGuide: "My → 이용권 → 해지",
  },
  {
    id: "disneyplus",
    name: "Disney+",
    url: "https://www.disneyplus.com",
    category: "entertainment",
    logoStyle: "wordmark",
    isSubscription: true,
    subscriptionCost: 9900,
    billingCycle: "monthly",
    currency: "KRW",
    deleteDifficulty: "easy",
    deleteGuide: "프로필 → 계정 → 구독 → 해지",
  },
  {
    id: "bugs",
    name: "벅스",
    url: "https://www.bugs.co.kr",
    category: "entertainment",
    logoStyle: "symbol_color",
    isSubscription: true,
    subscriptionCost: 7900,
    billingCycle: "monthly",
    currency: "KRW",
    deleteDifficulty: "easy",
    deleteGuide: "마이페이지 → 이용권 → 해지",
  },
  {
    id: "melon",
    name: "멜론",
    url: "https://www.melon.com",
    category: "entertainment",
    logoStyle: "symbol_color",
    isSubscription: true,
    subscriptionCost: 10900,
    billingCycle: "monthly",
    currency: "KRW",
    deleteDifficulty: "medium",
    deleteGuide: "마이메뉴 → 이용권 → 해지",
  },
  {
    id: "tving",
    name: "티빙",
    url: "https://www.tving.com",
    category: "entertainment",
    logoStyle: "wordmark",
    isSubscription: true,
    subscriptionCost: 9500,
    billingCycle: "monthly",
    currency: "KRW",
    deleteDifficulty: "easy",
    deleteGuide: "MY → 이용권 관리 → 해지",
  },

  // ──────── 업무 ────────
  {
    id: "slack",
    name: "Slack",
    url: "https://slack.com",
    category: "work",
    logoStyle: "symbol_color",
    isSubscription: false,
    deleteDifficulty: "medium",
    deleteGuide: "워크스페이스 관리자에게 요청 또는 계정 설정에서 삭제",
  },
  {
    id: "notion",
    name: "Notion",
    url: "https://www.notion.so",
    category: "work",
    logoStyle: "symbol_simple",
    isSubscription: false,
    deleteDifficulty: "easy",
    deleteGuide: "Settings → Account → Delete my account",
  },
  {
    id: "google-workspace",
    name: "Google Workspace",
    url: "https://workspace.google.com",
    category: "work",
    logoStyle: "symbol_color",
    isSubscription: true,
    subscriptionCost: 7200,
    billingCycle: "monthly",
    currency: "KRW",
    deleteDifficulty: "medium",
    deleteGuide: "관리 콘솔 → 구독 → 해지",
  },
  {
    id: "microsoft365",
    name: "Microsoft 365",
    url: "https://www.microsoft365.com",
    category: "work",
    logoStyle: "symbol_color",
    isSubscription: true,
    subscriptionCost: 8900,
    billingCycle: "monthly",
    currency: "KRW",
    deleteDifficulty: "medium",
    deleteGuide: "account.microsoft.com → 서비스 및 구독 → 취소",
  },
  {
    id: "figma",
    name: "Figma",
    url: "https://www.figma.com",
    category: "work",
    logoStyle: "symbol_simple",
    isSubscription: false,
    deleteDifficulty: "easy",
    deleteGuide: "Settings → Account → Delete account",
  },
  {
    id: "zoom",
    name: "Zoom",
    url: "https://zoom.us",
    category: "work",
    logoStyle: "symbol_simple",
    isSubscription: false,
    deleteDifficulty: "easy",
    deleteGuide: "프로필 → 계정 관리 → 계정 해지",
  },

  // ──────── 게임 ────────
  {
    id: "steam",
    name: "Steam",
    url: "https://store.steampowered.com",
    category: "gaming",
    logoStyle: "symbol_simple",
    isSubscription: false,
    deleteDifficulty: "hard",
    deleteGuide: "Steam 지원 → 계정 삭제 요청 (구매 내역 모두 삭제됨)",
  },
  {
    id: "epic-games",
    name: "Epic Games",
    url: "https://www.epicgames.com",
    category: "gaming",
    logoStyle: "symbol_simple",
    isSubscription: false,
    deleteDifficulty: "hard",
    deleteGuide: "계정 → 일반 설정 → 계정 삭제 요청",
  },
  {
    id: "nexon",
    name: "넥슨",
    url: "https://www.nexon.com",
    category: "gaming",
    logoStyle: "wordmark",
    isSubscription: false,
    deleteDifficulty: "hard",
    deleteGuide: "넥슨 홈페이지 → 내 정보 → 회원탈퇴 (30일 유예)",
  },
  {
    id: "netmarble",
    name: "넷마블",
    url: "https://www.netmarble.com",
    category: "gaming",
    logoStyle: "wordmark",
    isSubscription: false,
    deleteDifficulty: "medium",
    deleteGuide: "넷마블 홈페이지 → 마이페이지 → 회원탈퇴",
  },
  {
    id: "kakaogames",
    name: "카카오게임즈",
    url: "https://www.kakaogames.com",
    category: "gaming",
    logoStyle: "symbol_color",
    isSubscription: false,
    deleteDifficulty: "medium",
    deleteGuide: "카카오계정 설정에서 연결 해제",
  },

  // ──────── 교육 ────────
  {
    id: "udemy",
    name: "Udemy",
    url: "https://www.udemy.com",
    category: "education",
    logoStyle: "wordmark",
    isSubscription: false,
    deleteDifficulty: "easy",
    deleteGuide: "Account Settings → Close Account",
  },
  {
    id: "class101",
    name: "클래스101",
    url: "https://class101.net",
    category: "education",
    logoStyle: "wordmark",
    isSubscription: true,
    subscriptionCost: 19900,
    billingCycle: "monthly",
    currency: "KRW",
    deleteDifficulty: "medium",
    deleteGuide: "설정 → 회원탈퇴",
  },
  {
    id: "inflearn",
    name: "인프런",
    url: "https://www.inflearn.com",
    category: "education",
    logoStyle: "wordmark",
    isSubscription: false,
    deleteDifficulty: "easy",
    deleteGuide: "설정 → 회원탈퇴",
  },
  {
    id: "coursera",
    name: "Coursera",
    url: "https://www.coursera.org",
    category: "education",
    logoStyle: "wordmark",
    isSubscription: false,
    deleteDifficulty: "easy",
    deleteGuide: "Account Settings → Delete Account",
  },

  // ──────── 클라우드 ────────
  {
    id: "google-drive",
    name: "Google Drive",
    url: "https://drive.google.com",
    category: "cloud",
    logoStyle: "symbol_color",
    isSubscription: false,
    deleteDifficulty: "hard",
    deleteGuide: "Google 계정과 연동 — Google 계정 삭제 시 함께 삭제",
  },
  {
    id: "icloud",
    name: "iCloud",
    url: "https://www.icloud.com",
    category: "cloud",
    logoStyle: "symbol_simple",
    isSubscription: true,
    subscriptionCost: 1100,
    billingCycle: "monthly",
    currency: "KRW",
    deleteDifficulty: "hard",
    deleteGuide: "Apple ID로 관리 — Apple 계정 삭제 필요",
  },
  {
    id: "dropbox",
    name: "Dropbox",
    url: "https://www.dropbox.com",
    category: "cloud",
    logoStyle: "symbol_simple",
    isSubscription: false,
    deleteDifficulty: "easy",
    deleteUrl: "https://www.dropbox.com/account/delete",
    deleteGuide: "Settings → Account → Delete account",
  },
  {
    id: "onedrive",
    name: "OneDrive",
    url: "https://onedrive.live.com",
    category: "cloud",
    logoStyle: "symbol_color",
    isSubscription: false,
    deleteDifficulty: "medium",
    deleteGuide: "Microsoft 계정과 연동 — Microsoft 계정 설정에서 관리",
  },

  // ──────── 개발 ────────
  {
    id: "github",
    name: "GitHub",
    url: "https://github.com",
    category: "dev",
    logoStyle: "symbol_simple",
    isSubscription: false,
    deleteDifficulty: "easy",
    deleteUrl: "https://github.com/settings/admin",
    deleteGuide: "Settings → Account → Delete your account",
  },
  {
    id: "gitlab",
    name: "GitLab",
    url: "https://gitlab.com",
    category: "dev",
    logoStyle: "symbol_color",
    isSubscription: false,
    deleteDifficulty: "easy",
    deleteGuide: "User Settings → Account → Delete account",
  },
  {
    id: "vercel",
    name: "Vercel",
    url: "https://vercel.com",
    category: "dev",
    logoStyle: "symbol_simple",
    isSubscription: false,
    deleteDifficulty: "easy",
    deleteGuide: "Settings → General → Delete Account",
  },
  {
    id: "aws",
    name: "AWS",
    url: "https://aws.amazon.com",
    category: "dev",
    logoStyle: "wordmark",
    isSubscription: false,
    deleteDifficulty: "hard",
    deleteGuide: "계정 설정 → 계정 해지 (모든 리소스 삭제 후 가능)",
  },
  {
    id: "netlify",
    name: "Netlify",
    url: "https://www.netlify.com",
    category: "dev",
    logoStyle: "symbol_simple",
    isSubscription: false,
    deleteDifficulty: "easy",
    deleteGuide: "User Settings → Delete account",
  },

  // ──────── 기타 ────────
  {
    id: "naver",
    name: "네이버",
    url: "https://www.naver.com",
    category: "other",
    logoStyle: "wordmark",
    isSubscription: false,
    deleteDifficulty: "medium",
    deleteUrl: "https://nid.naver.com/user2/help/leaveId",
    deleteGuide: "네이버 → 내정보 → 회원탈퇴",
  },
  {
    id: "daum-kakao",
    name: "다음/카카오",
    url: "https://www.daum.net",
    category: "other",
    logoStyle: "symbol_color",
    isSubscription: false,
    deleteDifficulty: "medium",
    deleteGuide: "카카오계정 → 설정 → 탈퇴하기",
  },
  {
    id: "google",
    name: "Google",
    url: "https://www.google.com",
    category: "other",
    logoStyle: "wordmark",
    isSubscription: false,
    deleteDifficulty: "hard",
    deleteUrl: "https://myaccount.google.com/delete-services-or-account",
    deleteGuide: "Google 계정 → 데이터 및 개인정보 보호 → 계정 삭제",
  },
  {
    id: "apple",
    name: "Apple",
    url: "https://www.apple.com",
    category: "other",
    logoStyle: "symbol_simple",
    isSubscription: false,
    deleteDifficulty: "hard",
    deleteUrl: "https://privacy.apple.com",
    deleteGuide: "privacy.apple.com에서 계정 삭제 요청",
  },
  {
    id: "kakao",
    name: "카카오톡",
    url: "https://www.kakaocorp.com",
    category: "other",
    logoStyle: "symbol_color",
    isSubscription: false,
    deleteDifficulty: "medium",
    deleteGuide: "카카오톡 → 설정 → 개인/보안 → 카카오 계정 → 탈퇴",
  },
  {
    id: "naver-plus",
    name: "네이버플러스 멤버십",
    url: "https://nid.naver.com/membership/join",
    category: "shopping",
    logoStyle: "wordmark",
    isSubscription: true,
    subscriptionCost: 4900,
    billingCycle: "monthly",
    currency: "KRW",
    deleteDifficulty: "easy",
    deleteGuide: "네이버 → 멤버십 → 해지",
  },
  {
    id: "coupang-eats",
    name: "쿠팡이츠",
    url: "https://www.coupangeats.com",
    category: "shopping",
    logoStyle: "wordmark",
    isSubscription: false,
    deleteDifficulty: "medium",
    deleteGuide: "쿠팡 계정과 통합 — 쿠팡 탈퇴 시 함께 삭제",
  },
  {
    id: "baemin",
    name: "배달의민족",
    url: "https://www.baemin.com",
    category: "shopping",
    logoStyle: "cute_character",
    isSubscription: false,
    deleteDifficulty: "easy",
    deleteGuide: "My배민 → 설정 → 회원탈퇴",
  },
];

export const SERVICE_CATEGORIES = [
  { key: "all", label: "전체" },
  { key: "sns", label: "SNS" },
  { key: "shopping", label: "쇼핑" },
  { key: "finance", label: "금융" },
  { key: "entertainment", label: "엔터" },
  { key: "work", label: "업무" },
  { key: "gaming", label: "게임" },
  { key: "education", label: "교육" },
  { key: "cloud", label: "클라우드" },
  { key: "dev", label: "개발" },
  { key: "other", label: "기타" },
] as const;
